### ISSUE TITLE
Unexpected exclusion of CNVs in the result table

### ISSUE THREAD

**Issue by maehler** [hydra-genetics/reports#74]
If a CNV passes the filter in one of the callers, then any CNV from another caller, regardless of whether it itself has passed the filter or not, should also show up in the results table. It seems this is not always the case.

@jonca79, @jfr019: please add some information on cases where you have seen this behaviour. For which caller does the variant show up, and for which one doesn't it show up? Feel free to add any more information you think could be relevant.

**Comment by maehler** [comment]
I actually see this type of problem in one of the reports that Sanja sent out as a practice case for interpreting the report. In this case there are two variants detected by cnvkit (DEL) that corresponds to a copy-normal segment identified by GATK. The cnvkit variants show up in the filtered table, but the corresponding copy-normal segment from GATK are hidden when the filter is turned on.

Now I at least have something to get me started.

**Comment by maehler** [comment]
I have now been able to reproduce the issue in the integration test. For me this happened when I had multiple segments in cnvkit that overlapped a single large segment in GATK, and the first of the cnvkit segments was COPY_NORMAL. This doesn't seem to be the general case though. In the report mentioned above, there are also multiple cnvkit segments overlapping a single GATK segment, but here the first segment in cnvkit is *not* COPY_NORMAL.

I'll work on a fix for the thing I managed to reproduce and see if this also fixes other, similar cases.

**Comment by jfr019** [comment]
Här är de fall där jag såg oväntat resultat:
Issue #1:
pathology_purecn-rapport (Tumor cell content: 1.0)

I den filtrerade rapporten visas
GATK	
chr11	ATM	532 366	133 134 330	COPY_NORMAL	2,01	0,074
Cnvkit	
chr11	ATM	54 758 853	78 907 493	COPY_NORMAL	1,97	0,478
chr17	BRCA1	41 192 674	421 120	COPY_NORMAL	2,45	0,242

Båda visar ATM som COPY_NORMAL. Låg BAF i GATK är anledningen till ATM visas i filtrerade listan där. (Vad är cut-off?) 

GATK visar dock inte BRCA1 i den filtrerade listan, och den står som COPY_NORMAL i den ofiltrerade listan, med BAF 0,493:
chr17	BRCA1, NF1, RAD51C, TP53	901 872	79 888 729	COPY_NORMAL	2,02	0,493

Issue #2:
purecn -rapporten (Tumor cell content: 0.22 (purecn))

I den filtrerade rapporten visas
GATK
chr11	ATM	532 366	133 134 330	COPY_NORMAL	2,06	0,074
cnvkit
chr11	ATM	54 758 853	78 907 493	COPY_NORMAL	1,87	0,399
chr13	BRCA2, RB1	32 962 556	57 166 640	DEL	1,37	0,408

Båda visar ATM som COPY_NORMAL, p.g.a. låg BAF hos GATK.

BRCA2, RB1 som detekteras av cnvkit finns som COPYNORMAL i GATK – borde den då inte komma med i den filtrerade listan?

chr13	BRCA2, RB1	19 292 855	95 764 635	COPY_NORMAL	1,90	0,496

Håller man muspekaren över CN-värdet här får man match till två CNV från cnvkit, deletionen + en copy_normal:
chr13	BRCA2	18 993 607	13 967 679	COPY_NORMAL	2,08	0,402
chr13	BRCA2, RB1	32 962 556	57 166 640	DEL	1,37	0,408

**Comment by jfr019** [comment]
Jag ser nu att båda mina exempel är samma det du beskriver ovan. Bra!

**Comment by maehler** [comment]
I now think that everything works as expected. I added tests for some of the cases that I have seen, and they all now pass: #75
